<?php

namespace AppBundle\Repository;

/**
 * CamionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CamionRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarSoloCamionesVisibles($idEmpresa){        
		
        return $this->getEntityManager()
                    ->createQuery(' SELECT c
                                    FROM AppBundle:Camion c
                                    WHERE c.camVisible = 1
                                    AND c.empresa = :idEmpresa')
                    ->setParameter('idEmpresa', $idEmpresa)
                    ->getResult();
    }
}
