<?php

namespace AppBundle\Repository;

/**
 * CentroDeAcopioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroDeAcopioRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarSoloCentrosVisibles(){        
        $qb=$this->createQueryBuilder('c')
                 ->add('from', 'AppBundle:CentroDeAcopio c')
                 ->add('where', 'c.cenVisible =:visible')
                 ->setParameter('visible',1);
        return $qb->getQuery()->getResult();
    }
    
    public function obtenerLatitudYLongitud($direccion){        
        
        $data = array('status'=>'Error', 'latitud'=>0, 'longitud'=>0 );
        $geo = file_get_contents('http://maps.googleapis.com/maps/api/geocode/json?address='.urlencode($direccion).'&sensor=false');
        $respuesta = json_decode($geo, true);
        if ($respuesta['status'] == 'OK') {
            $data['status']  = 'OK';
            $data['latitud']  = $respuesta['results'][0]['geometry']['location']['lat'];
            $data['longitud'] = $respuesta['results'][0]['geometry']['location']['lng'];
        }
        return $data;
    }
            
}
