<?php

namespace AppBundle\Repository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{
     public function buscarSoloClientesVisibles($idEmpresa){        
        $qb=$this->createQueryBuilder('c')
                 ->add('from', 'AppBundle:Cliente c')
                 ->add('where', 'c.cliVisible =:visible')
                 ->setParameter('visible',1);
        return $qb->getQuery()->getResult();
    }
}
