<?php

namespace AppBundle\Repository;

/**
 * ConfiguracionAmplRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionAmplRepository extends \Doctrine\ORM\EntityRepository
{
}
