<?php

namespace AppBundle\Repository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarSoloEmpresasVisibles(){        
        $qb=$this->createQueryBuilder('e');
        $qb->add('from', 'AppBundle:Empresa e');
        $qb->add('where', 'e.empVisible =:visible');
        $qb->setParameter('visible',1);
        return $qb->getQuery()->getResult();
    }
    
}
