<?php

namespace AppBundle\Repository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarSoloEmpresasVisibles(){        
        $qb=$this->createQueryBuilder('e')
                 ->add('from', 'AppBundle:Empresa e')
                 ->add('where', 'e.empVisible =:visible')
                 ->setParameter('visible',1);
        return $qb->getQuery()->getResult();
    }
    
}
