<?php

namespace AppBundle\Repository;

/**
 * FecuenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FecuenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
