<?php

namespace AppBundle\Repository;

/**
 * FeriadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeriadosRepository extends \Doctrine\ORM\EntityRepository
{
}
