<?php

namespace AppBundle\Repository;

/**
 * FrecuenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrecuenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
