<?php

namespace AppBundle\Repository;

/**
 * OperadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperadorRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarSoloOperadoresVisibles($idEmpresa){               
        return $this->getEntityManager()
        ->createQuery(' SELECT o
                        FROM AppBundle:Operador o
                        LEFT JOIN o.usuario u
                        WHERE o.opeVisible = 1
                        AND u.empresa = :idEmpresa')
        ->setParameter('idEmpresa', $idEmpresa)
        ->getResult();
    }

    public function existeElUsuario($rut){
        return $this->getEntityManager()
        ->createQuery(' SELECT u
                        FROM AppBundle:User u
                        WHERE u.username = :usuario')
        ->setParameter('usuario', $rut)
        ->getResult();
    }
}
