<?php

namespace AppBundle\Repository;

/**
 * OperadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperadorRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarSoloOperadoresVisibles($idEmpresa){        
        $qb=$this->createQueryBuilder('o')
                 ->add('from', 'AppBundle:Operador o')
                 ->add('where', 'o.opeVisible=1');
                 //->add('where', 'o.empresa =:idEmpresa')
                // ->setParameter('idEmpresa',$idEmpresa);
        return $qb->getQuery()->getResult();
    }
}
