<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Proceso;

/**
 * ProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoRepository extends \Doctrine\ORM\EntityRepository
{
    public function obtenerProcesosDeLaEmpresa($idEmpresa){

        $query = $this->createQueryBuilder('p')
                ->where('p.empresa = ?1')
                ->orderBy('p.id', 'DESC')
                ->setParameter(1, $idEmpresa);      
        return $query->getQuery()->getResult();
    }

    public function agregarActualizarProceso($empresa,$clientes){
        
        $proceso = $this->findBy(array('empresa'=>$empresa,'prcEstado'=>0)); 
        $totalcli = count($clientes);
        $mensaje ='';
        $observacion='Debe validar este proceso para que pueda ser ejecutado.';
        if(count($proceso) === 0){
            $proceso = new Proceso();
            $mensaje ='Nuevo proceso creado correctamente.';
        }else{
            $proceso = $proceso[0];
            $mensaje ='Proceso actualizado.';
        }
        $proceso->setPrcCantidadClientes($totalcli)
                ->setPrcFecha(new \DateTime(date('Y-m-d H:s:i')))
                ->setPrcEstado(0)
                ->setPrcValidado(false)
                ->setEmpresa($empresa)
                ->setPrcObservacion($observacion)
                ->setPrcTermino(new \DateTime(date('Y-m-d H:s:i')));  

        $em = $this->getEntityManager();
        $em->persist($proceso);
        $em->flush();
        return $mensaje;
    }
    
    public function procesoEnEsperaDeEjecucion($validado,$estado){
        
        return $this->getEntityManager()
                ->createQuery(' SELECT p
                                FROM AppBundle:Proceso p
                                WHERE p.prcValidado= :validado
                                AND p.prcEstado= :estado')
                ->setParameter('validado', $validado)
                ->setParameter('estado', $estado)
                ->getResult();
    }
}
