<?php

namespace AppBundle\Repository;

/**
 * ProcesoClientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoClientesRepository extends \Doctrine\ORM\EntityRepository
{
}
