<?php

namespace AppBundle\Repository;

/**
 * ProcesoCamionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoCamionesRepository extends \Doctrine\ORM\EntityRepository
{
}
