<?php

namespace AppBundle\Repository;

/**
 * RutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RutaRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarRutasDelMes($mes,$anio,$idEmpresa){

            return $this->getEntityManager()
            ->createQuery(' SELECT r
                            FROM AppBundle:Ruta r
                            LEFT JOIN r.camion c
                            LEFT JOIN c.operador o
                            LEFT JOIN o.usuario u
                            WHERE u.empresa = :idEmpresa
                            AND SUBSTRING(r.rtaFecha,6,2)= :mes
                            AND SUBSTRING(r.rtaFecha,1,4)= :anio
                                    ')
            ->setParameter('idEmpresa', $idEmpresa)->setParameter('mes', $mes)->setParameter('anio', $anio)
            ->getResult();
    }

    public function buscarRutasDelDia($dia,$mes,$anio,$idEmpresa){

            return $this->getEntityManager()
            ->createQuery(' SELECT r
                            FROM AppBundle:Ruta r
                            LEFT JOIN r.camion c
                            LEFT JOIN c.operador o
                            LEFT JOIN o.usuario u
                            WHERE u.empresa = :idEmpresa
                            AND SUBSTRING(r.rtaFecha,1,4)= :anio
                            AND SUBSTRING(r.rtaFecha,6,2)= :mes
                            AND SUBSTRING(r.rtaFecha,9,2)= :dia')
            ->setParameter('idEmpresa', $idEmpresa)
            ->setParameter('anio', $anio)
            ->setParameter('mes', $mes)
            ->setParameter('dia', $dia)
            ->getResult();
    }
}