<?php

namespace AppBundle\Repository;

/**
 * RutaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RutaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
