<?php

namespace AppBundle\Repository;

/**
 * ThetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThetaRepository extends \Doctrine\ORM\EntityRepository
{
}
