<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function verificarQueNoExistaElUsuario($username){        
        $qb=$this->createQueryBuilder('u')
                 ->add('from', 'AppBundle:User u')
                 ->add('where', 'u.username =:Username')
                 ->setParameter('Username',$username);
        return $qb->getQuery()->getResult();
    }

    public function buscarSoloUsuariosVisibles(){
        $qb=$this->createQueryBuilder('u')
                 ->add('from', 'AppBundle:User u')
                 ->add('where', 'u.visible =1');
        return $qb->getQuery()->getResult();  
    }
    
    public function obtenerTokenParaElUsuario(){        
        $token = md5(time().'..'.'prysaarc'.'.,'.date('Ymdhis'));
        return $token;
    }

}
