
security:
    encoders:
        AppBundle\Entity\User:
          algorithm: bcrypt
          cost: 4

    providers:
        user_db:
          entity:
            class: AppBundle:User
            property: username
        api_key_user_provider:
          id: api_key_user_provider

    firewalls:
        dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
        secured_area:
          switch_user: true
          pattern: ^/secured
          provider: user_db
          form_login:
              login_path: /
              check_path: /secured/login_check
              default_target_path: /secured/index
          logout:
              path:   /secured/logout
              target: /
        api_firewall:
          pattern: ^/api #O como sea que se llame la ruta que se quiere proteger con este método.
          stateless: true
          simple_preauth:
              authenticator: apikey_authenticator
          provider: api_key_user_provider

    access_control:
        - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /token-authentication, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/secured/superadmin, roles: [ROLE_SUPERADMIN]}
        - { path: ^/secured/admin, roles: [ROLE_ADMIN]}
        - { path: ^/secured/operador, roles: [ROLE_OPERATOR]}
        - { path: ^/secured/cliente, roles: [ROLE_CLIENT]}
         