# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider

    apikey_authenticator:
            class:  AppBundle\Security\ApiKeyAuthenticator
            public: false
            arguments: ["@doctrine.orm.entity_manager"]

    switch.command:
            class:  AdminBundle\Command\SwitchProcessCommand
            tags: [{ name: console.command }] # This makes it a command
            calls:
                - [setContainer, ['@service_container']]
    create.command:
            class:  AdminBundle\Command\CreateDataFileCommand
            tags: [{ name: console.command }] # This makes it a command
            calls:
                - [setContainer, ['@service_container']]

