# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider

    apikey_authenticator:
            class:  AppBundle\Security\ApiKeyAuthenticator
            public: false
            arguments: ["@doctrine.orm.entity_manager"]