users:
  type: rest
  resource: APIBundle\Controller\UsersController
  
empresas:
  type: rest
  resource: APIBundle\Controller\EmpresasController
  
usuarios:
  type: rest
  resource: APIBundle\Controller\UsuariosController
  
centros:
  type: rest
  resource: APIBundle\Controller\CentrosController
  
comunas:
  type: rest
  resource: APIBundle\Controller\ComunasController
  
camiones:
  type: rest
  resource: APIBundle\Controller\CamionesController
    
operadores:
  type: rest
  resource: APIBundle\Controller\OperadoresController
  
clientes:
  type: rest
  resource: APIBundle\Controller\ClientesController
  
rutas:
  type: rest
  resource: APIBundle\Controller\RutasController
  
frecuencias:
  type: rest
  resource: APIBundle\Controller\FrecuenciasController
  
procesos:
  type: rest
  resource: APIBundle\Controller\ProcesosController
  
misrutas:
  type: rest
  resource: APIBundle\Controller\MisRutasController

visitas:
  type: rest
  resource: APIBundle\Controller\VisitasController

detalleRuta:
  type: rest
  resource: APIBundle\Controller\DetalleRutaController

comentariosVisitas:
  type: rest
  resource: APIBundle\Controller\ComentariosVisitasController
