<?php

namespace AppBundle\Repository\Entity;

/**
 * ProcesoClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoClienteRepository extends \Doctrine\ORM\EntityRepository
{
}
